---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hipster-ingress
  namespace: hipster-shop
  annotations:
     kubernetes.io/ingress.className: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: "store.tbello.bio"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: monitoring-ingress
#   namespace: monitoring
#   annotations:
#      kubernetes.io/ingress.className: "nginx"
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: "stors.tbello.bio"
#       http:
#         paths:
#           - path: /monitoring
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus
#                 port:
#                   number: 9090
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: monitoring-ingress
#   namespace: monitoring
#   annotations:
#      kubernetes.io/ingress.className: "nginx"
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: "stors.tbello.bio"
#       http:
#         paths:
#           - path: /grafana
#             pathType: Prefix
#             backend:
#               service:
#                 name: grafana
#                 port:
#                   number: 3000
