---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hipster-ingress
  namespace: hipster-shop
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: fbayomide.studio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-monitoring-ingress
  namespace: monitoring
  annotations:
     kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "prometheus.fbayomide.studio"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-monitoring-ingress
  namespace: monitoring
  annotations:
     kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "grafana.fbayomide.studio"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
