---
name: Terraform Validation
env:
  AWS_BUCKET_KEY: ${{ secrets.AWS_BUCKET_KEY }}
  S3_BACKEND_BUCKET: ${{secrets.AWS_STATE_BUCKET_NAME}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}

on:
  push:
    branches:
      - test
  pull_request:
    branches: ['test']

jobs:
  deploy_app_on_EKS:
    runs-on: ubuntu-latest
    name: Deploy app on amazon eks cluster
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Kubectl
    