---
name: Container Deployment
env:
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
on:
  push:
    branches: ['test']
    # paths: ['./src/*']
  pull_request:
    branches: ['test']
    # paths: ['./src/*']

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      # run: sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    # - name: Extract metadata (tags, labels) for Docker  
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: "./src/adservice"
        push: true
        # tags: ${{ steps.meta.outputs.tags }}
        tags: adservice:latest
        # labels: ${{ steps.meta.outputs.labels }}
    - name: Inspect Docker Image
      run: |
        docker image inspect adservice:latest
    # - name: Build docker image
    #   working-directory: ./src/adservice
    #   run: sudo docker build . -t microservice:adservice

    # - name: Push to docker image
    #   working-directory: ./src/adservice
    #   run: sudo docker image push microservice:adservice
