name: Terraform Validation
env:
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
  DOCKER_USER: ${{secrets.DOCKER_USER}} 
on:
  push:
    branches:
      - [ $default-branch ]
  pull_request:
    branches:
      - [ $default-branch ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_ACCESS_TOKEN

    - name: Build docker image
      working_directory: ./src/adservice
      run: docker build . -t micorservice:adservice

    - name: Push to docker image
      working_directory: ./src/adservice
      run: docker image push microservice:adservice
