name: Deploy App on Cluster
env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
on:
  push:
    branches: ['test']
    paths: ['./deploy_manifest/*', '.github/workflows/deploy.yml']
  pull_request:
    branches: ['test']
    paths: ['./deploy_manifest/*', '.github/workflows/deploy.yml']

jobs:
  deploy_app_on_EKS:
    runs-on: ubuntu-latest
    name: Deploy app on amazon eks cluster
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
  
    # - name: Deploy Monitoring Yaml
    #   run: |
    #     aws eks update-kubeconfig --name group-17-eks --region ${{ env.AWS_REGION }}
    #     kubectl apply -f monitoring_manifest  

    # - name: Deploy Hipster Shop 
    #   working-directory: ./deploy_manifest
    #   run: |
    #     aws eks update-kubeconfig --name group-17-eks --region ${{ env.AWS_REGION }}
    #     kubectl apply -f hipster_shop_deploy.yml
    #     kubectl apply -f ingress.yml

   
    # - name: DELETE Monitoring and hipster namespace
    #   run: |
    #     aws eks update-kubeconfig --name group-17-eks --region ${{ env.AWS_REGION }}
    #     kubectl delete namespace monitoring
    #     kubectl delete namespace hipster-shop

