---
name: Terraform Validation
env:
  AWS_BUCKET_KEY: ${{ secrets.AWS_BUCKET_KEY }}
  S3_BACKEND_BUCKET: ${{secrets.AWS_STATE_BUCKET_NAME}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}

on:
  push:
    branches:
      - test
  pull_request:
    branches: ['test']
    # paths: ['./terraform/*']
jobs:
  terraform_validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init, format and validate
        run: |
          echo "** Running Terraform Init **"
          terraform init \
            -backend-config="bucket=${{env.S3_BACKEND_BUCKET}}" \
            -backend-config="key=${{env.AWS_BUCKET_KEY}}" \
            -backend-config="region=${{env.AWS_REGION}}" \
            -backend-config="secret_key=${{env.AWS_SECRET_ACCESS_KEY}}" \
            -backend-config="access_key=${{env.AWS_ACCESS_KEY}}"
          
          echo "** Runing Terraform Format Check **"
          terraform fmt 
          
          echo " Running Terraform Validate"
          terraform validate

          echo "Running Terraform Plan"
          terraform plan
          